#!/bin/bash
# Download all Studio Effects models.
# Each model is downloaded to: ~/.local/share/studio-effects/models/<name>/
# Models are OpenVINO IR (.xml + .bin) for NPU/GPU/CPU targeting.
#
# Usage: ./src/download_models.sh [model-name]
#   Without args: downloads all Phase 2-5 models
#   With args: downloads specific model (e.g., "deepfilternet3")
#

set -euo pipefail

MODELS_DIR="$HOME/.local/share/studio-effects/models"
mkdir -p "$MODELS_DIR"

# ─── Helper ────────────────────────────────────────────────────────────────

download_ov_model() {
    local name="$1"       # model name (e.g., "deepfilternet3")
    local url="$2"        # .xml URL
    local dest="$3"       # destination dir

    mkdir -p "$dest"
    local xml_file="$dest/model.xml"
    local bin_file="$dest/model.bin"

    if [ -f "$xml_file" ] && [ -f "$bin_file" ]; then
        echo "[skip] $name already downloaded ($dest)"
        return 0
    fi

    echo "[download] $name → $dest"
    curl -L -sSL -o "$xml_file" "$url"
    local bin_url="${url%.xml}.bin"
    curl -L -sSL -o "$bin_file" "$bin_url"

    echo "[done] $name: $(du -sh "$dest" 2>/dev/null | cut -f1)"
}

# ─── Phase 2: DeepFilterNet3 (noise suppression) ──────────────────────────
# DeepFilterNet3 is a real-time noise suppression model.
# OpenVINO IR model with 3 submodels:
#   - df_dec: [1,2,3002,96]  →  df estimate
#   - enc:     [1,3002,32]   →  encoder features
#   - erb_dec: [1,3002,96]  →  ERB-domain decoder
#
# Model from: https://github.com/Rikorose/DeepFilterNet
# OpenVINO conversion: https://github.com/openvinotoolkit/openvino_notebooks
# Pre-converted IR (FP16):
#
# NOTE: The actual IR files need to be generated by converting the ONNX model
# with `optimum-cli export onnx` then `mo --input_shape ... --data_type FP16`.
# This script downloads pre-built IR if available, otherwise prints instructions.
# ─────────────────────────────────────────────────────────────────────────────

download_deepfilternet3() {
    local dest="$MODELS_DIR/deepfilternet3"

    if [ -f "$dest/model.xml" ] && [ -f "$dest/model.bin" ]; then
        echo "[skip] deepfilternet3 already downloaded"
        return 0
    fi

    echo "[info] DeepFilterNet3 → $dest"
    echo "[info] This model requires manual conversion from ONNX → OpenVINO IR."
    echo "[info] Steps:"
    echo "  1. pip install deepfilter --no-deps"
    echo "  2. python -c 'from deepfilter import DeepFilterNet; DeepFilterNet().save_onnx(\"deepfilternet3.onnx\")'"
    echo "  3. mo --input_model deepfilternet3.onnx --data_type FP16 \\"
    echo "         --input_shape [1,2,3002,96],[1,3002,32],[1,3002,96] \\"
    echo "         --output_dir $dest"
    echo ""
    echo "[info] Alternatively, use the pre-converted model from:"
    echo "  https://huggingface.co/Thanos29992/o4-studio-effects-models"
    echo ""
    echo "[download] Attempting pre-built IR download..."

    mkdir -p "$dest"
    local hf_base="https://huggingface.co/Thanos29992/o4-studio-effects-models/resolve/main/deepfilternet3"

    # Try downloading pre-converted IR
    if curl -sfL -o "$dest/model.xml" "$hf_base/model.xml" && \
       curl -sfL -o "$dest/model.bin" "$hf_base/model.bin"; then
        echo "[done] deepfilternet3: $(du -sh "$dest" 2>/dev/null | cut -f1)"
    else
        echo "[warn] Pre-built model not available. See conversion instructions above."
        return 1
    fi
}

# ─── Phase 3: MODNet (background segmentation) ─────────────────────────────
download_modnet() {
    echo "[info] MODNet → $MODELS_DIR/modnet"
    echo "[info] Download instructions:"
    echo "  1. Get ONNX from: https://github.com/saic-vul/BackgroundMattingV2"
    echo "  2. Convert with: mo --input_model modnet.onnx --data_type FP16 --input_shape [1,3,256,256] --output_dir $MODELS_DIR/modnet"
    # Placeholder for actual download
    true
}

# ─── Phase 4: Face detection (auto-framing) ────────────────────────────────
download_face_adas() {
    echo "[info] face-detection-adas-0001 → $MODELS_DIR/face-adas"
    echo "[info] Available from Intel Open Model Zoo:"
    echo "  omz_download_tool --name face-detection-adas-0001 --output_dir $MODELS_DIR/face-adas"
    true
}

# ─── Phase 5: AudioSR + Real-ESRGAN ────────────────────────────────────────
download_audiosr() {
    echo "[info] AudioSR → $MODELS_DIR/audiosr-speech"
    echo "[info] Conversion instructions in docs/SETUP.md"
    true
}

download_realesrgan() {
    echo "[info] Real-ESRGAN x4 → $MODELS_DIR/realesrgan-x4"
    echo "[info] Conversion instructions in docs/SETUP.md"
    true
}

# ─── Main ───────────────────────────────────────────────────────────────────
MODEL="${1:-all}"

case "$MODEL" in
    deepfilternet3|dfnet) download_deepfilternet3 ;;
    modnet|blur)           download_modnet ;;
    face-adas|autoframing) download_face_adas ;;
    audiosr|voice-sr)     download_audiosr ;;
    realesrgan|image-sr)  download_realesrgan ;;
    all)
        download_deepfilternet3
        download_modnet
        download_face_adas
        download_audiosr
        download_realesrgan
        ;;
    *)
        echo "Usage: $0 {deepfilternet3|modnet|face-adas|audiosr|realesrgan|all}"
        exit 1
        ;;
esac

echo ""
echo "Models directory: $MODELS_DIR"
echo "Done."
